### DISCUSSION TITLE
Incorrect server response after file upload

### DISCUSSION THREAD

**Discussion by dima-gr** [Studio-42/elFinder#3410] [Q&A]
After loading the pdf file, the elfinder gives an error. The file is physically uploaded to the folder, but an error is thrown when displaying the list of uploaded files. If i delete this file, the list will be displayed normally

Error:
Incorrect server response.
An error occurred on the server side.
HTTP error 500

installed packages
```
behat/transliterator v1.3.0 String transliterator
composer/package-versions-deprecated 1.11.99.1 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
doctrine/annotations 1.13.1 Docblock Annotations Parser
doctrine/cache 2.1.1 PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections 1.6.7 PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common 3.1.2 PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection...
doctrine/dbal 2.13.2 Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations v0.5.3 A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/doctrine-bundle 2.4.2 Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle 3.1.1 Symfony DoctrineMigrationsBundle
doctrine/event-manager 1.1.1 The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector 2.0.3 PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator 1.4.0 A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer 1.2.1 PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations 3.2.0 PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database sche...
doctrine/orm 2.9.3 Object-Relational-Mapper for PHP
doctrine/persistence 2.2.1 The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter 1.1.1 a PHP SQL highlighting library
easycorp/easyadmin-bundle v3.4.3 Admin generator for Symfony applications
egulias/email-validator 3.1.1 A library for validating emails against several RFCs
friendsofphp/proxy-manager-lts v1.0.5 Adding support for a wider range of PHP versions to ocramius/proxy-manager
friendsofsymfony/ckeditor-bundle 2.3.0 Provides a CKEditor integration for your Symfony project.
gedmo/doctrine-extensions v3.1.0 Doctrine2 behavioral extensions
helios-ag/fm-elfinder-bundle 10.1 ElFinder bundle, adds ElFinder file manager to your Symfony project
imagine/imagine 1.2.4 Image processing for PHP 5.3
jms/metadata 2.5.0 Class/method/property metadata management in PHP
laminas/laminas-code 4.4.2 Extensions to the PHP Reflection API, static code scanning, and code generation
liip/imagine-bundle 2.6.1 This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
monolog/monolog 2.3.2 Sends your logs to files, sockets, inboxes, databases and various web services
nikic/php-parser v4.12.0 A PHP parser written in PHP
phpdocumentor/reflection-common 2.2.0 Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock 5.2.2 With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver 1.4.0 A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache 2.0.0 Common interface for caching libraries
psr/container 1.1.1 Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher 1.0.0 Standard interfaces for event handling.
psr/link 1.1.1 Common interfaces for HTTP links
psr/log 1.1.4 Common interface for logging libraries
sensio/framework-extra-bundle v5.6.1 This bundle provides a way to configure your controllers with annotations
stof/doctrine-extensions-bundle v1.6.0 Integration of the gedmo/doctrine-extensions with Symfony
studio-42/elfinder 2.1.59 File manager for web
swiftmailer/swiftmailer v6.2.7 Swiftmailer, free feature-rich PHP mailer
symfony/asset v5.2.12 Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit v5.2.12 Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache v5.2.12 Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts v2.4.0 Generic abstractions related to caching
symfony/config v5.2.12 Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console v5.2.12 Eases the creation of beautiful and testable command line interfaces
symfony/css-selector v5.2.12 Converts CSS selectors to XPath expressions
symfony/debug-bundle v5.2.12 Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection v5.2.12 Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts v2.4.0 A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge v5.2.12 Provides integration for Doctrine with various Symfony components
symfony/dom-crawler v5.2.12 Eases DOM navigation for HTML and XML documents
symfony/dotenv v5.2.12 Registers environment variables from a .env file
symfony/error-handler v5.2.12 Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher v5.2.12 Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0 Generic abstractions related to dispatching event
symfony/expression-language v5.2.12 Provides an engine that can compile and evaluate expressions
symfony/filesystem v5.2.12 Provides basic utilities for the filesystem
symfony/finder v5.2.12 Finds files and directories via an intuitive fluent interface
symfony/flex v1.13.3 Composer plugin for Symfony
symfony/form v5.2.12 Allows to easily create, process and reuse HTML forms
symfony/framework-bundle v5.2.12 Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client v5.2.12 Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts v2.4.0 Generic abstractions related to HTTP clients
symfony/http-foundation v5.2.12 Defines an object-oriented layer for the HTTP specification
symfony/http-kernel v5.2.13 Provides a structured process for converting a Request into a Response
symfony/intl v5.2.12 Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer v5.2.12 Helps sending emails
symfony/maker-bundle v1.33.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime v5.2.12 Allows manipulating MIME messages
symfony/monolog-bridge v5.2.12 Provides integration for Monolog with various Symfony components
symfony/monolog-bundle v3.7.0 Symfony MonologBundle
symfony/notifier v5.2.12 Sends notifications via one or more channels (email, SMS, ...)
symfony/options-resolver v5.2.12 Provides an improved replacement for the array_replace PHP function
symfony/phpunit-bridge v5.3.4 Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme v1.23.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring v1.23.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80 v1.23.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/polyfill-uuid v1.23.0 Symfony polyfill for uuid functions
symfony/process v5.2.12 Executes commands in sub-processes
symfony/property-access v5.2.12 Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info v5.2.12 Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge v5.2.12 Provides integration for ProxyManager with various Symfony components
symfony/routing v5.2.12 Maps an HTTP request to a set of configuration variables
symfony/security-bundle v5.2.12 Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core v5.2.12 Symfony Security Component - Core Library
symfony/security-csrf v5.2.12 Symfony Security Component - CSRF Library
symfony/security-guard v5.2.12 Symfony Security Component - Guard
symfony/security-http v5.2.12 Symfony Security Component - HTTP Integration
symfony/serializer v5.2.12 Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts v2.4.0 Generic abstractions related to writing services
symfony/stopwatch v5.2.12 Provides a way to profile code
symfony/string v5.2.11 Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/swiftmailer-bundle v3.5.2 Symfony SwiftmailerBundle
symfony/translation v5.2.12 Provides tools to internationalize your application
symfony/translation-contracts v2.4.0 Generic abstractions related to translation
symfony/twig-bridge v5.2.12 Provides integration for Twig with various Symfony components
symfony/twig-bundle v5.2.12 Provides a tight integration of Twig into the Symfony full-stack framework
symfony/uid v5.2.11 Provides an object-oriented API to generate and represent UIDs
symfony/validator v5.2.12 Provides tools to validate values
symfony/var-dumper v5.2.12 Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter v5.2.12 Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link v5.2.12 Manages links between resources
symfony/web-profiler-bundle v5.2.13 Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle v1.12.0 Integration with your Symfony app & Webpack Encore!
symfony/yaml v5.2.12 Loads and dumps YAML files
twig/extra-bundle v3.3.1 A Symfony bundle for extra Twig extensions
twig/twig v3.3.2 Twig, the flexible, fast, and secure template language for PHP
vich/uploader-bundle 1.18.0 Ease file uploads attached to entities
webmozart/assert 1.10.0 Assertions to validate method input/output with nice error messages.
```

php version

```
PHP 8.0.3 (cli) (built: Mar 27 2021 07:17:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```

elfinder config

```
#assets_path: / # default is /assets, this is where css/js elfinder files are
instances:
    default:
        locale: '%locale%' # defaults to current request locale
        editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
        relative_path: true #default true, will produce absolute urls to specified file(s)
        #editor_template: custom template for your editor # default null
        #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
        #fullscreen: true|false # default is true, applies to simple and ckeditor editors
        #theme: smoothness # jquery theme, default is 'smoothness'
        #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
        connector:
            roots:
                uploads:
                    driver: LocalFileSystem
                    path: uploads
                    upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-excel']
                    upload_deny: ['all']
                    upload_max_size: 100M # also file upload sizes restricted in php.ini
```

fos_ck_editor:

```
default_config: default
configs:
    default:
        contentsCss: 'ckeditor/css/ckeditor_content.css'
        filebrowserBrowseRoute: elfinder
        filebrowserBrowseRouteParameters: []
        extraPlugins: "image2, youtube"
        pasteFromWordRemoveStyles: true
        pasteFromWordPromptCleanup: true
        bodyClass: wrapper container text
        height: 70vh
        youtube_responsive: true
        youtube_related: false
        youtube_disabled_fields: ['txtEmbed', 'chkAutoplay']
        removePlugins: 'iframe'
        stylesSet: default
```

in php logs

```
[2021-09-13T15:54:05.612773+03:00] php.CRITICAL: Uncaught Error: Undefined constant "ELFINDER_IMAGEMAGICK_PS" {"exception":"[object] (Error(code: 0): Undefined constant \"ELFINDER_IMAGEMAGICK_PS\" at /var/www/html/vendor/studio-42/elfinder/php/elFinderVolumeDriver.class.php:5570)"} []
[2021-09-13T15:54:05.613772+03:00] request.CRITICAL: Uncaught PHP Exception Error: "Undefined constant "ELFINDER_IMAGEMAGICK_PS"" at /var/www/html/vendor/studio-42/elfinder/php/elFinderVolumeDriver.class.php line 5570 {"exception":"[object] (Error(code: 0): Undefined constant \"ELFINDER_IMAGEMAGICK_PS\" at /var/www/html/vendor/studio-42/elfinder/php/elFinderVolumeDriver.class.php:5570)"} []
```
