### ISSUE TITLE
Notification popup enhancements

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1036]
Add notification popup position to configuration like notifyPosition: ['center','center'] ..
```javascript
var options = {
    url  : 'php/connector.php',
    notifyPosition : ['center','middle'] // ['center','bottom'], ['left','top'] ...
}
$('#elfinder').elfinder(options);
```
Add more infos to notifications, now they just say 'open file...', will be better if it was 'opening something.txt'

**Comment by nao-pon** [comment]
@ERROPiX How about use CSS.

ref. https://github.com/nao-pon/elFinder-nightly/issues/8

ex.  ['center','middle']
```css
div.elfinder-dialog-notify {
  top: 50% !important;
  left: 0 !important;
  right: 0 ;
  margin: auto auto;
  transform: translateY(-50%);
}
```
