### ISSUE TITLE
Customize the icon base on MIME type?

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1436]
![image 3](https://cloud.githubusercontent.com/assets/14356169/15698208/b99a21b8-27f4-11e6-91b0-ea8d306d6ce5.png)

In the file manager, I would like to set different logos for different file type, mainly the MS office file type.

E.g. MS Words and MS Excel file have different type of icon, how to achieve that? Thanks

For Excel icons:
.xls      application/vnd.ms-excel
.xlsx     application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

For Words icons:
.doc      application/msword
.docx     application/vnd.openxmlformats-officedocument.wordprocessingml.document

**Comment by nao-pon** [comment]
@leo1989work You can use specific icon with custom CSS.

e.g.
```css
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-excel,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-excel-addin-macroEnabled-12,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-excel-sheet-binary-macroEnabled-12,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-excel-sheet-macroEnabled-12,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-excel-template-macroEnabled-12,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-openxmlformats-officedocument-spreadsheetml-sheet,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-openxmlformats-officedocument-spreadsheetml-template {
	background-image: url("URL TO YOUR EXCEL ICON");
	background-position: center center;
	background-repeat: no-repeat;
	background-size: contain;
}

.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-word,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-word-document-macroEnabled-12,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-ms-word-template-macroEnabled-12,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-openxmlformats-officedocument-wordprocessingml-document,
.elfinder-cwd-icon.elfinder-cwd-icon-vnd-openxmlformats-officedocument-wordprocessingml-template {
	background-image: url("URL TO YOUR WORD ICON");
	background-position: center center;
	background-repeat: no-repeat;
	background-size: contain;
}
```
