### ISSUE TITLE
Disabling notifications after creating item

### ISSUE THREAD

**Issue by kkotowick** [Studio-42/elFinder#1822]
When I create a new folder, it pops up with a green box saying "New Folder Complete" with a button that says "Open a folder". Is there any way to disable this?

Thanks!

**Comment by nao-pon** [comment]
@kkotowick There is no setting item, but it can be hidden by CSS.

e.g. ([Online demo](http://jsbin.com/digunu/edit?css,output))
```css
.elfinder-toast .toast-success {
	visibility: hidden;
}
```
