### ISSUE TITLE
Make toolbar buttons larger?

### ISSUE THREAD

**Issue by RobAley** [Studio-42/elFinder#1839]
elfinder is great, but I struggle to see the toolbar buttons properly due to their size.
 
Is there a way to make the toolbar buttons larger? (I'm guessing not due to the use of fixed size images rather than e.g. SVG or fontawsome type icons). 

If not, is there an easy way to hide the toolbar and hook up my own buttons? E.g. is there appropriate classes, ids or similar that I can give to buttons (e.g. created with fontawsome which I use for other buttons in my app) that will call the appropriate events and activate/disable themselves appropriately? Or is there a list of events that I can listen for / call?

Thanks

**Comment by nao-pon** [comment]
@RobAley You can control CSS by class name `elfinder-button`, `elfinder-button-icon` of toolbar's buttons. The button HTML is 

```html
<div class="ui-state-default elfinder-button" title="[cmd name]">
    <span class="elfinder-button-icon elfinder-button-icon-[cmd]"></span>
    <span class="elfinder-button-text" style="display: none;">[cmd name]</span>
</div>
```

e.g.

```css
.elfinder .elfinder-button {
    width: 20px;
    height: 20px;
}
.elfinder-button-icon {
    zoom: 1.25;
    -moz-transform: scale(1.25);
    -moz-transform-origin: top left;
}
```
