### ISSUE TITLE
audio/mpeg(.mp3) & video/mpeg(.mpeg/.mpg)

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2155]
```
.elfinder-cwd-icon-audio-mpeg:after,
.elfinder-cwd-icon-audio-mpeg          { background: url('../img/items/mp3-audio-icon-big.ico') no-repeat; }

.elfinder-cwd-icon-video-mpeg:after,
.elfinder-cwd-icon-video-mpeg { background: url('../img/items/MPEG-video-icon-big.ico') no-repeat; }
```

this code doesn't work & only available for both `.elfinder-cwd-icon-mpeg`

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM The icon has classes elfinder-cwd-icon-[type] and elfinder-cwd-icon-[sub type]. so video/mpeg has elfinder-cwd-icon-video and elfinder-cwd-icon-mpeg.

**Comment by CodeLyokoXtEAM** [comment]
if 'elfinder-cwd-icon-video' use all video including .avi .mp4 .wma .etc icon are same.
But I have different icon for each files.
![image](https://user-images.githubusercontent.com/18566890/29484847-186e8b2c-84e5-11e7-8776-2c75d9432a60.png)

if use 'elfinder-cwd-icon-mpeg' .mp3 file is gone to mpeg icon
So How I can change without mixing .mp3 & .mpeg ?

**Comment by nao-pon** [comment]
Please learn to control to priority of CSS. :-)

e.g.
```css
.elfinder-cwd-icon-audio.elfinder-cwd-icon-mpeg:after,
.elfinder-cwd-icon-audio.elfinder-cwd-icon-mpeg          { background: url('../img/items/mp3-audio-icon-big.ico') no-repeat; }

.elfinder-cwd-icon-video.elfinder-cwd-icon-mpeg:after,
.elfinder-cwd-icon-video.elfinder-cwd-icon-mpeg { background: url('../img/items/MPEG-video-icon-big.ico') no-repeat; }
```
