### ISSUE TITLE
Disable Save As in resize dialog

### ISSUE THREAD

**Issue by mozan** [Studio-42/elFinder#2644]
As in subject. Is there a way to achieve this without modifying the source?

**Comment by nao-pon** [comment]
@mozan There is no option to disable, so please hide it in CSS.

```css
.elfinder-dialog-resize .ui-dialog-buttonset .elfinder-btncnt-1 {
	display: none;
}
```
