### ISSUE TITLE
elfinder page redirecting to login page

### ISSUE THREAD

**Issue by disha2018** [Studio-42/elFinder#2796]
Hi, I am using ''helios-ag/fm-elfinder-bundle" in symfony 3.4, following are the settings details:

composer: `require: { "helios-ag/fm-elfinder-bundle": "^9.1", "php": "^7.1" .....}, "config": {
        "component-dir": "web/assets",`
config.yml:
```
cmf_media:
    upload_file_role:        ROLE_CAN_UPLOAD_FILE
    use_elfinder:            auto
    use_imagine:             auto

fm_elfinder:
    instances:
        default:
            locale: "%locale%"
            editor: ckeditor
            include_assets: true
            connector:
                debug: true
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['all']
                        upload_max_size: 2M 
```

security.yml: 
```
security:
    role_hierarchy:
        ROLE_CCI_RSA_LOGIN_LABS_APP_APPSPECIFIC_CMS_VGTACCESS:
            - ROLE_USER
            - ROLE_VGT_USER
        ROLE_CCI_RSALOGINLABS_APP_APPSPECIFICCMS_CSRACCESS:
            - ROLE_USER
            - ROLE_CSR_USER
        ROLE_CCI_RSA_LOGIN_LABS_APP_APPSPECIFIC_CMS_WIZARDACCESS:
            - ROLE_USER
            - ROLE_WIZARD_USER
        ROLE_CCI_RSALOGINLABS_APP_APPSPECIFICCMS_ADMINACCESS:
            - ROLE_SUPER_ADMIN

    providers:
        ldap:
           id: imag_ldap.security.user.provider

    encoders:
        IMAG\LdapBundle\User\LdapUser: plaintext

    access_control:
		.
		.
		.
        - { path: ^/efconnect, roles: [ROLE_CCI_RSALOGINLABS_APP_APPSPECIFICCMS_ADMINACCESS, ROLE_CCI_RSA_LOGIN_LABS_APP_APPSPECIFIC_CMS_WIZARDACCESS] }
        - { path: ^/elfinder, roles: [ROLE_CCI_RSALOGINLABS_APP_APPSPECIFICCMS_ADMINACCESS, ROLE_CCI_RSA_LOGIN_LABS_APP_APPSPECIFIC_CMS_WIZARDACCESS] }
```
AppKernal & routing settings are also done, bit when url is hit the page shows the pop up with error "Invalid backend response. Data is not JSON." & login form HTML.  After refreshing page it goes to login page again

Please help.

Disha.
