### ISSUE TITLE
search filter option

### ISSUE THREAD

**Issue by alexandrovsergii** [Studio-42/elFinder#2803]
Is it possible to make Filename as the default search filter option and completely remove the expanding block with other filter options?

**Comment by nao-pon** [comment]
@alexandrovsergii Please set commandsOptions.search.searchTypes to empty and hide it in the style sheet.

```javascript
commandsOptions : {
	search : {
		searchTypes : {}
	}
}
```

```css
.elfinder .buttonset.elfinder-search-type {
	display: none;
}
```
