### ISSUE TITLE
'tmbSize' not working

### ISSUE THREAD

**Issue by hilarl** [Studio-42/elFinder#323]
i am trying to change the size of the thumbnails displayed and i tried by changing the value on the tmbSize option but it doesnt seem to change the size of the thumbs. i also tried changing the value of the tmbBgColor but doesnt change either.

According to the docs:

tmbSize
Thumbnails size in pixels. Thumbnails are square

Data type: integer
Default value: 48

My Code:

```
        $(document).ready(function() {
            var elf = $('#elfinder').elfinder({
                url : 'php/connector.php',  // connector URL (REQUIRED)
                commands : [
                                                 'reload', 'home', 'up', 'getfile', 'quicklook', 
                                                 'download', 'rm', 'rename', 'mkdir', 'upload', 'copy', 
                                                 'cut', 'paste', 'search', 'info', 'view',
                                                 'sort'
                                                ],
                                    height: 520,
                                    tmbSize: 158,
                                    tmbBgColor: '#eee'

            }).elfinder('instance');
        });
```

**Comment by standus** [comment]
Still this doesnot work well, because css styles are hardcoded for 48x48 120x80, 52x52. And folder icons sprite are only 48x48, etc.

**Comment by nao-pon** [comment]
@standus It is possible by CSS customization.

for example - [online demo](http://jsbin.com/dawiy/edit?html,output)
```css
.elfinder-cwd-view-icons .elfinder-cwd-file {
	width: 220px;
	height: 180px;
}
.elfinder-cwd-view-icons .elfinder-cwd-file-wrapper {
	width: 152px;
	height: 152px;
}
.elfinder-cwd-icon {
	-moz-transform-origin: top center;
	-moz-transform: scale(3);
	zoom: 3;
}
```
