### ISSUE TITLE
elFinder "dropbox" div not uploading files?

### ISSUE THREAD

**Issue by marktopper** [Studio-42/elFinder#827]
In elFinder's upload command the Drag & Drop box method (in code call [dropbox](https://github.com/Studio-42/elFinder/blob/2.x/js/commands/upload.js#L70-L99)) doesn't work for me.

The data which the [upload function](https://github.com/Studio-42/elFinder/blob/2.x/js/commands/upload.js#L33) gets sent using the dropbox is the following:

```
Object
    files:
        length: 0
    type: "data"
```

While if I do select files to upload via the "Select Files To Upload"-button, the data is the following:

```
Object
    input: input
    files:
        0:
            lastModifiedDate: Mon Apr 07 2014 15:22:44 GMT+0200 (CEST)
            name: "image-1.jpg"
            size: 164112
            type: "image/jpeg"
        1:
            lastModifiedDate: Mon Apr 07 2014 15:22:44 GMT+0200 (CEST)
            name: "image-2.jpg"
            size: 164112
            type: "image/jpeg"
        2:
            lastModifiedDate: Mon Apr 07 2014 15:22:44 GMT+0200 (CEST)
            name: "image-3.jpg"
            size: 164112
            type: "image/jpeg"
        length: 3
```

The box I am talking about is the "Drop Files Here" box, which you can see on the screenshot below:
![screen shot 2014-04-10 at 15 26 41](https://cloud.githubusercontent.com/assets/2232539/2667921/c69a1bc0-c0b3-11e3-9aae-3e54fd225ef4.png)

Anyone have any solutions for this?
