### ISSUE TITLE
Display long file names in "cwd" in 2 rows

### ISSUE THREAD

**Issue by troex** [Studio-42/elFinder#89]
http://trash.mrtech.ru/~junkyard/tmp/elfinder-two-line-filenames.png

Such look can be made by adding:

```css
.elfinder-cwd-view-icons .elfinder-cwd-filename {
  max-height: 30px;
  white-space: wrap;
}
```

I would like this to be in future release, this makes more like real Finder look.

Tested in Chrome.
